### PR TITLE
feat: section services

### PR DESCRIPTION
**Pull request by mustapha-ghlissi**
Section services: What Datara can do for you !

### CODE REVIEW

**Comment by IvanDerlich** [comment]
Good

**Comment by IvanDerlich** [comment]
image

**Comment by IvanDerlich** [comment]
image

**Comment by IvanDerlich** [comment]
image

**Comment by IvanDerlich** [comment]
Let's ignore this comment for now
https://github.com/IvanDerlich/datara/pull/10#issuecomment-2258766777
Fix the other comments and I'll figure out a solution for this

**Comment by mustapha-ghlissi** [comment]
> image


fixed

**Pull request merged**
